"""Developer-only export of the agreed design. Deployed Bitrix needs PHP, not Python.

Generated include files can be edited through Bitrix. Re-export only in the source
checkout, review the diff, and do not overwrite CMS edits without merging them.
"""
import re
import shutil
from pathlib import Path

from src.render import render_page

ROOT = Path(__file__).resolve().parent
SITE = ROOT / 'bitrix/site'
TEMPLATE = SITE / 'local/templates/aib_etrn'
GUARD = "<?php\nif (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) { die(); }\n?>\n"


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('\n'.join(line.rstrip() for line in text.splitlines()) + '\n', encoding='utf-8')


def native_js():
    js = (ROOT / 'src/app.js').read_text(encoding='utf-8')
    js = js.replace("document.querySelector('[data-lead-form]')", "document.querySelector('[data-bitrix-form] form')", 1)
    js = re.sub(r'^const (?:contactTypeInputs|formEndpoint|retrySeconds|duplicateMinutes|submitButtonContent) = .*;\n', '', js, flags=re.M)
    start = js.index('function showContactField(')
    end = js.index('function hideSelectionToast()', start)
    js = js[:start] + js[end:]
    start = js.index('function storageRead(')
    end = js.index('symptomButtons.forEach((button)', start)
    js = js[:start] + js[end:]
    js = js.replace('    const problem = form.elements.problem;\n', '')
    js = js.replace("    const wasSelected = button.getAttribute('aria-pressed') === 'true';", """    const problem = form?.querySelector('[data-aib-field="problem"] textarea');
    if (!problem) {
      document.querySelector('#request')?.scrollIntoView({ behavior: 'smooth' });
      return;
    }
    const wasSelected = button.getAttribute('aria-pressed') === 'true';""")
    js = js.replace("showContactField('phone');", '')
    # Native Bitrix POST: never use the standalone API, FormSubmit, or JS fetch.
    js += '\n' + (ROOT / 'bitrix/native-form.js').read_text(encoding='utf-8')
    assert 'fetch(' not in js and 'buildPayload' not in js and 'validateForm' not in js
    return """// Generated by build_bitrix.py. UI only; form processing belongs to Bitrix.
(() => {
  function boot() {
    if (window.aibBitrixBootstrapped) return;
    window.aibBitrixBootstrapped = true;
""" + js + """
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot, { once: true });
  else boot();
})();
"""


def build():
    page = render_page({'mode': 'production', 'site_url': 'https://aib-build.example/',
                        'privacy_url': 'https://aib-build.example/privacy',
                        'consent_url': 'https://aib-build.example/consent',
                        'offer_url': 'https://aib-build.example/offer', 'delivery_confirmed': True})
    page = page.replace('assets/aib-logo.png', '/local/templates/aib_etrn/assets/aib-logo.png')
    for key, placeholder in [('offer_url', 'https://aib-build.example/offer'),
                             ('privacy_url', 'https://aib-build.example/privacy'),
                             ('consent_url', 'https://aib-build.example/consent'),
                             ('confidentiality_url', 'assets/documents/confidentiality.pdf?v=20260923')]:
        page = page.replace(placeholder, "<?= \\Aib\\Etrn\\documentUrl('" + key + "') ?>")
    body = page.split('  >\n', 1)[1].split('</body>', 1)[0]
    header, rest = body.split('<main id="main">', 1)
    main, footer = rest.split('</main>', 1)
    includes = SITE / 'include/aib'
    write(includes / 'header.php', GUARD + header)
    footer = footer.replace('<a class="inline-link" href="<?= \\Aib\\Etrn\\documentUrl(\'privacy_url\') ?>" target="_blank" rel="noopener">Обработка данных</a>',
                            "<?php if (\\Aib\\Etrn\\settings()['privacy_url'] !== ''): ?>"
                            '<a class="inline-link" href="<?= \\Aib\\Etrn\\documentUrl(\'privacy_url\') ?>" target="_blank" rel="noopener">Обработка данных</a>'
                            '<?php endif; ?>')
    write(includes / 'footer.php', GUARD + footer)
    chunks = re.split(r'\n(?=      <section\b)', main.strip('\n'))
    names = ['hero', 'conditions', 'problems', 'scope', 'process', 'price', 'trust', 'faq', 'request']
    assert len(chunks) == len(names), 'Review renderer section boundaries before exporting'
    for name, chunk in zip(names[:-1], chunks[:-1]):
        chunk = chunk.replace('Поможем решить проблему с ЭТрН</h1>', '<?php $APPLICATION->ShowTitle(false); ?></h1>')
        write(includes / (name + '.php'), GUARD + chunk)
    document = re.search(r'<section class="form-documents".*?</section>', chunks[-1], re.S)
    assert document
    write(includes / 'documents.php', GUARD + document.group())
    write(includes / 'landing.php', "<?php\nif (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) { die(); }\n"
          + '\n'.join(f"$APPLICATION->IncludeFile('/include/aib/{name}.php', [], ['MODE' => 'php', 'NAME' => 'Блок {name}']);" for name in names))
    css = (ROOT / 'src/styles.css').read_text(encoding='utf-8')
    # Keep the admin panel outside global resets, retain the existing layout selectors.
    css = css.replace('*,\n*::before,\n*::after', '.aib-landing,\n.aib-landing *,\n.aib-landing *::before,\n.aib-landing *::after')
    css = re.sub(r'(?m)^(button|input|textarea|select|a)(?=[,{ ])', r'.aib-landing \1', css)
    css = css.replace('body {', 'body.aib-page {').replace(':focus-visible {', '.aib-landing :focus-visible {')
    css += '\n' + (ROOT / 'bitrix/compatibility.css').read_text(encoding='utf-8')
    write(TEMPLATE / 'template_styles.css', css)
    write(TEMPLATE / 'assets/ui.js', native_js())
    shutil.copyfile(ROOT / 'src/assets/aib-site.png', TEMPLATE / 'assets/aib-logo.png')
    documents = SITE / 'upload/aib-etrn/documents'
    documents.mkdir(parents=True, exist_ok=True)
    for name in ('offer.pdf', 'confidentiality.pdf'):
        shutil.copyfile(ROOT / 'src/assets/documents' / name, documents / name)
    print('Built Bitrix PHP 8.3 template: ' + str(SITE))


if __name__ == '__main__':
    build()
