// Uses inputs generated by form.result.new; their POST names/values stay intact.
function markFormStarted() {
  if (formStarted) return;
  formStarted = true;
  track('form_start');
}
form?.addEventListener('input', markFormStarted);
form?.addEventListener('change', markFormStarted);

form?.querySelectorAll('.aib-question').forEach((field, index) => {
  const controls = [...field.querySelectorAll('input:not([type="hidden"]), textarea, select')];
  const legend = field.querySelector('legend');
  if (legend) legend.id = `aib-question-${index}`;
  controls.forEach((control) => {
    if (!control.hasAttribute('aria-labelledby') && legend) control.setAttribute('aria-labelledby', legend.id);
    if (field.querySelector('.field-error')) control.setAttribute('aria-invalid', 'true');
  });
  // Browser convenience only. Required fields/validators must be configured in Bitrix.
  if (field.dataset.required === 'Y' && controls.length === 1) controls[0].required = true;
});

form?.addEventListener('submit', (event) => {
  if (isSubmitting) { event.preventDefault(); return; }
  isSubmitting = true;
  // Do not disable the submit button: Bitrix needs web_form_submit in the POST.
  submitButton?.setAttribute('aria-disabled', 'true');
  if (formStatus) formStatus.textContent = 'Передаём заявку…';
  // Native browser POST continues to the action from FORM_HEADER.
});
window.addEventListener('pageshow', () => {
  isSubmitting = false;
  submitButton?.removeAttribute('aria-disabled');
  if (formStatus) formStatus.textContent = '';
});

const bitrixError = document.querySelector('[data-bitrix-errors]');
const bitrixSuccess = document.querySelector('[data-bitrix-success]');
if (bitrixError || bitrixSuccess) {
  const message = bitrixError || bitrixSuccess;
  message.focus({ preventScroll: true });
  document.querySelector('#request')?.scrollIntoView({ behavior: 'auto' });
  track(bitrixError ? 'form_error' : 'lead_accepted', bitrixError ? { fields: 'bitrix' } : {});
}
